### PR TITLE
[admin] Implementation of password change function 

### LINKED ISSUE #23: Implement the ability to change the administrator's password.
* Place a “change password” button in the administrators table.
* When this button is clicked, display a form containing the "Password" label and a password field.
* When this form is submitted, update the administrator's `password_hash` if the password is not empty.

### PR DESCRIPTION
**Pull request by kkana6624**
# Related Issues
Close #23 

# Changes
* Added password change function
* Added unit test
* Run `mix format`

# Review Perspective
* Whether the content of the implementation is appropriate
* Whether UI behaviour is appropriate
* I have added a unit test. Check for problems with directory structure
* I implemented as much as I could guess. Please point out any missing features.

# note

* re-create pull resuqst #27

### CODE REVIEW

**Comment by kkana6624** [comment]
@kuroda 
I have verified that the automated test I added will complete successfully.
However, the existing test outputs the following error

```
1) test GET / (LiveWebServerWeb.PageControllerTest)
     test/live_web_server_web/controllers/page_controller_test.exs:4
     ** (RuntimeError) expected content-type for html, got: "text/plain; charset=utf-8"
     code: assert html_response(conn, 200) =~ "Peace of mind from prototype to production"
     stacktrace:
       (phoenix 1.7.14) lib/phoenix/test/conn_test.ex:319: Phoenix.ConnTest.response_content_type/2
       (phoenix 1.7.14) lib/phoenix/test/conn_test.ex:388: Phoenix.ConnTest.html_response/2
       test/live_web_server_web/controllers/page_controller_test.exs:6: (test)
```

I think this is because line 11 of `page_controller.ex` is as follows and returns text.

```elixir
_ -> text(conn, "Not Found: #{uri.path}")
```

I figured that if I were to modify the test case it would look something like this.
```elixir
defmodule LiveWebServerWeb.PageControllerTest do
  use LiveWebServerWeb.ConnCase

  test "GET /", %{conn: conn} do
    conn = get(conn, ~p"/")
    #assert html_response(conn, 200) =~ "Peace of mind from prototype to production"
    assert response(conn, 200) =~ "Not Found: /"
  end
end
```

I did not commit the modification here because I could not accurately determine the intent of the existing test case.
How should this one be handled?

**Comment by kkana6624** [comment]
@kuroda 
Please review.

**Comment by kuroda** [comment]
@kkana6624 

> However, the existing test outputs the following error

This test script is automatically created when the Phoenix app skeleton is created. Delete that file as it is no longer needed.

The commit that deletes the file should be separated from the main commit.

**Comment by kuroda** [comment]
@kkana6624 

> Please review.

See https://github.com/oiax/live_web_server/issues/23#issuecomment-2400998546

**Comment by kkana6624** [comment]
@kuroda 
Review remarks have been corrected. 
Please review again.

**Review by kuroda — APPROVED** [review]

**Pull request merged**
